apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: web-app
        image: nginx:latest  # Ganti dengan image Docker aplikasi kamu
        ports:
        - containerPort: 80
        env:
        - name: DB_HOST
          value: "mysql"
        - name: DB_PASS
          value: "password123"